blogSection = false
logo = "/uploads/logo.png"
icon = "/uploads/fav_icon.png"
tagline = "Best Techs Reviewed"
contacteMail = "gamingtechies76@gmail.com"
headerText = "Gaming Techies supported by its audience. When you purchase through our links, we may earn an affiliate commission at no additional cost to you."
footerText = "Gaming Techies supported by its audience. When you purchase through our links, we may earn an affiliate commission at no additional cost to you."
img_section = []

[fonts]
bodyFont = "Poppins"
heading = "Poppins"

[home_section]
section1 = "Style 1"
section1Cat = "Buying Guides"
section2 = "Style 1"
section2Cat = "Monitors"
section3 = "Style 1"
section3Cat = "Motherboards"
section4 = "Style 1"
section4Cat = "Headphones"

[colors]
mainColor = "#040404"
textColor = "#ffffff"
linkColor = "#2871de"
ctaColor = "#2871de"

[siteRobots]
catIndex = false

[open_graph]
meta_Description = "Gaming Techies is a professional online website that keeps you updated with all the gaming techs reviews, news and latest information."
image = "/uploads/banner_image.png"
FacebookPublisher = ""

[verifications]
googleSiteVerify = "<meta name=\"google-site-verification\" content=\"Zf3bwzwyh0LsAxEEJ6l0pyyJ2ljDK4wG-f1sGwnJXYs\" />"
BingWebmaster = "<meta name=\"msvalidate.01\" content=\"6D95BEBC76C7BC692B270BC832560CB0\" />"
PinterestVerify = ""

[social_accounts]
sitefbAccount = "https://www.facebook.com/gamingtechiesofficial"
sitetwitterAccount = "https://www.twitter.com/gamingtechies76"
siteinstagramAccount = "https://www.instagram.com/gamingtechies76/"
sitepinterestAccount = "https://www.pinterest.com/gamingtechies76/"
siteYouTubeAccount = "https://www.youtube.com/channel/UCV1YUero4LNDkktpq6ScEjw"

[[scroll_section]]
scrollcat = "Motherboards"

[[scroll_section]]
scrollcat = "Headphones"

[[scroll_section]]
scrollcat = "Graphics Cards"

[[scroll_section]]
scrollcat = "Keyboards"

[[scroll_section]]
scrollcat = "Monitors"

[[scroll_section]]
scrollcat = "Mouse"

[[scroll_section]]
scrollcat = "Routers and Modems"

[[scroll_section]]
scrollcat = "Cables"

[[scroll_section]]
scrollcat = "Chairs"

[[scroll_section]]
scrollcat = "PC Cases"

[[scroll_section]]
scrollcat = "PC Builds"

[[scroll_section]]
scrollcat = "Knowledge Base"

[post_setting]
featured_img = false